### ISSUE TITLE
DeclarationError: Undeclared identifier. (_exists(tokenId))

### ISSUE THREAD

**Issue by borailci** [PatrickAlphaC/hardhat-nft-fcc#107]
DeclarationError: Undeclared identifier.
  --> contracts/DynamicSVG_NFT.sol:79:14:
   |
79 |         if (!_exists(tokenId)) {
   |              ^^^^^^^
Error HH600: Compilation failed

I cannot find this function in ERC721.sol, is it changed or removed?

(Note: The source code of DynamicSVG_NFT.sol is same as the DynamicSVG_NFT.sol in the repo.

**Comment by stDean** [comment]
Hello, try this line instead

```solidity
 if (ownerOf(tokenId) != address(0)) {
      revert ERC721Metadata__URI_QueryFor_NonExistentToken();
    }
```
