### ISSUE TITLE
invalid contract address or ENS name

### ISSUE THREAD

**Issue by mertdeveci5** [PatrickAlphaC/hardhat-nft-fcc#21]
Hey everyone - trying to run the test deploys on the local network however have been getting the below error

```invalid contract address or ENS name (argument="addressOrName", value=undefined, code=INVALID_ARGUMENT, version=contracts/5.5.0)```

I checked typos on vrfCoordinatorV2Mock etc and corrected any of them. The error points to deploy\02-deploy-random-ipfs-nft.js:

I am really not able to understand what is wrong here. The only difference I have from Patrick's code is the below where I have to use `getContractAt` and he uses `getContract`, the reason being getContract simply does not exist and there is an error. Would love the help

``` javascript
 if (developmentChains.includes(network.name)) {
    let vrfCoordinatorV2Address;
    const vrfCoordinatorV2Mock = await ethers.getContractAt(
      "VRFCoordinatorV2Mock"
    );
```

**Comment by ABossOfMyself** [comment]
Do you have a "VRFCoordinatorV2Mock" in your contracts ?

**Comment by mertdeveci5** [comment]
I have "VRFCoordinatorV2Mock.sol" under test folder under contracts. Then again, the file also has an error below as to I cannot resolve why this pops up. Is this a version issue or smt? The current code from Patrick is relatively recent.

**Comment by ABossOfMyself** [comment]
send me your repo link. I will look into that.

**Comment by mertdeveci5** [comment]
Just added you to the repo, would appreciate the help

**Comment by ABossOfMyself** [comment]
kindly push your code to your repo.

**Comment by PatrickAlphaC** [comment]
`getContractAt` looks for an address at a specific address, since you're not passing the address, getContractAt won't work, you'll need to fix the issue with not having `getContract`.

**Comment by mertdeveci5** [comment]
Hey Patrick - thanks for this. Do you have an idea why this is happening? `getContract` simply does not exist and it throws an error. There might be a change with `hardhat-deploy-ethers` package I believe and `hardhat-ethers` as well since you made the tutorial?

**Comment by PatrickAlphaC** [comment]
`getContract` should come with hardhat deploy.

What happens when you do this:

```
git clone https://github.com/PatrickAlphaC/hardhat-nft-fcc
cd hardhat-nft-fcc
yarn
```

And then run the command you want. If it works in this repo, you'd just need to see what your repo is missing.

**Comment by mertdeveci5** [comment]
> kindly push your code to your repo.

pushed, sorry for the delay

**Comment by mertdeveci5** [comment]
> > kindly push your code to your repo.
> 
> pushed, sorry for the delay

resolved for now man - thank you much appreciated
