### ISSUE TITLE
invalid address  argument="vrfConsumerBaseV2"

### ISSUE THREAD

**Issue by ShabanGomaa** [PatrickAlphaC/hardhat-nft-fcc#22]
When I run 
```
yarn hardhat deploy
```
I got an error:
Error: invalid address (argument="address", value=undefined, code=INVALID_ARGUMENT, version=address/5.6.1) (argument="vrfConsumerBaseV2", value=undefined, code=INVALID_ARGUMENT, version=abi/5.6.4)

it is related to 02-deploy-random-ipfs-nft.js

Any suggestions?

**Comment by ABossOfMyself** [comment]
send me your repo link, I will look into that.

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
