### ISSUE TITLE
reverted with custom error 'InvalidConsumer()

### ISSUE THREAD

**Issue by mmuaaz** [PatrickAlphaC/hardhat-nft-fcc#55]
There seems to be an issue when running the deploy scripts, its been answered in the Discussions, please add this in the repo as comment or something that people make necessary changes to avoid the error.
The issue is the error:
```reverted with custom error 'InvalidConsumer()```

this issue is resolved by either downgrading the chainlink version by running:
```yarn add --dev @chainlink/contracts@0.4.1```

or a better solutions is editing your "02-deploy-random-ipfs-nft.js", and add following code after you deploy mock and random ipfs:
```
await vrfCoordinatorV2Mock.addConsumer(
        subscriptionId,
        randomIpfsNft.address
    )
```

the issue was addressed in the discussion: https://github.com/smartcontractkit/full-blockchain-solidity-course-js/discussions/1375

**Comment by kostissss** [comment]
I suppose you probably mean this code : 
`await vrfCoordinatorV2Mock.addConsumer(
        subscriptionId,
        randomIpfsNft.address
    )`

**Comment by mmuaaz** [comment]
Yes bro this code

**Comment by PatrickAlphaC** [comment]
Fixed in https://github.com/PatrickAlphaC/hardhat-nft-fcc/commit/4c3075e870555e99c0b76712c56a910e685df7e0

Thank you!
