### ISSUE TITLE
 Error: call revert exception; VM Exception while processing transaction: reverted with reason string "ERC721: invalid token ID"

### ISSUE THREAD

**Issue by simpleitis** [PatrickAlphaC/hardhat-nft-fcc#64]
In the last it block for the unit test for 'BasicNft'
```
const owner = await basicNft.ownerOf("1")
```

Should be replaced with 
```
const owner = await basicNft.ownerOf("0")
```

**Comment by PatrickAlphaC** [comment]
Thanks! Could you make a PR?

**Comment by simpleitis** [comment]
#65

**Comment by PatrickAlphaC** [comment]
Done https://github.com/PatrickAlphaC/hardhat-nft-fcc/pull/66

**Comment by BowTiedHeron** [comment]
just wanted to point out that this pr #71 reverses this logic @simpleitis.
the reason why it was reverted is because the test was failing.
it was solved by @AAYUSH-GUPTA-coder by reverting the change and by changing the pinata/sdk version to ^1.1.23

**Comment by simpleitis** [comment]
@BowTiedHeron Okay, maybe I was using the latest pinata sdk version and the chnages I made were required and all of the tests had passed

**Comment by simpleitis** [comment]
@BowTiedHeron I think I was using the latest pinata sdk version and the change I made was required to make all my tests pass
