### ISSUE TITLE
Error: expected array value (argument="dogTokenUris", value=undefined, code=INVALID_ARGUMENT, version=abi/5.7.0)

### ISSUE THREAD

**Issue by Chinwuba22** [PatrickAlphaC/hardhat-nft-fcc#83]
I get the above error when trying to deploy. (I'm currently in 21:59:12 part of the lesson). Please, here is my deploy-random-ipfs-nft file:
<img width="606" alt="image" src="https://user-images.githubusercontent.com/111384287/225576059-779f9afb-982c-4d1a-be4c-eda746eeb399.png">
<img width="487" alt="image" src="https://user-images.githubusercontent.com/111384287/225576140-f09c97a9-a712-4fa7-996b-89434a03a98c.png"> .

The error detail:
<img width="531" alt="image" src="https://user-images.githubusercontent.com/111384287/225576318-dea671ff-0eae-4be7-80d4-39658c905d46.png">

please any help will be much appreciated. Thank you

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
