### ISSUE TITLE
Error: No Contract deployed with name BasicNft

### ISSUE THREAD

**Issue by andrewpol777** [PatrickAlphaC/hardhat-nft-fcc#9]
Hello.
while you trying pass unit tests, you get an error in test/unit/basicNft.test.js:18:26
Error: No Contract deployed with name BasicNft

To fix it add to the end of file "01-deploy-basic-nft.js"

module.exports.tags = ["all", "basicnft"]

**Comment by PatrickAlphaC** [comment]
It's already in there no? 

https://github.com/PatrickAlphaC/hardhat-nft-fcc/blob/8bb515e864f0f82f5ddb88725192400f3dd8cdb8/deploy/01-deploy-basic-nft.js#L25

**Comment by andrewpol777** [comment]
Yes, Patrick, problem fixed, thnx


ср, 27 июл. 2022 г., 18:12 Patrick Collins ***@***.***>:
