### ISSUE TITLE
Cannot find artifact "MockV3Aggregator"

### ISSUE THREAD

**Issue by Devansh-Mehra** [PatrickAlphaC/hardhat-nft-fcc#91]
[
![1](https://github.com/PatrickAlphaC/hardhat-nft-fcc/assets/81522384/30f309ea-7124-421d-91f9-75f2df055ec2)
](url)

Someone help me with this issue , not able to resolve this one.
@PatrickAlphaC

**Comment by Devansh-Mehra** [comment]
Also I am not able to upload the files to pinata even after using pinata api key and other necessary values in .env.
Help me to resolve the issues.

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
