### ISSUE TITLE
Error occur while deploying mint.js to the sepolia network.

### ISSUE THREAD

**Issue by abdullahtanvir11** [PatrickAlphaC/hardhat-nft-fcc#93]
Error occurs on this command: "yarn hardhat deploy --network sepolia --tags mint"......
Basic NFT works fine but when it comes to dynamic svg nft it gives this error shown below. 
Error occurs on this command: "yarn hardhat deploy --network sepolia --tags mint"
Repository Link: https://github.com/abdullahtanvir11/hardhat-nft
![Capture](https://github.com/PatrickAlphaC/hardhat-nft-fcc/assets/109508166/ae383161-a83e-4f3d-a46e-465659a3a25e)

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
